import { useEffect, useState } from 'react';
import { BarChart3, BookOpen, DollarSign, Plus, Star, Users } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { instructorService } from '../services/instructor';

const InstructorDashboard = () => {
  const [stats, setStats] = useState({}); const [courses, setCourses] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const navigate = useNavigate();
  const load = async () => { setLoading(true); try { const [statsResponse, coursesResponse] = await Promise.all([instructorService.getStats(), instructorService.getCourses()]); setStats(statsResponse.data || {}); setCourses(coursesResponse.data || []); } catch (requestError) { setError(requestError.response?.data?.detail || 'Could not load your instructor dashboard'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const remove = async (id) => { if (!window.confirm('Delete this course?')) return; await instructorService.deleteCourse(id); load(); };
  if (loading) return <main className="page"><div className="spinner" /></main>; if (error) return <main className="page"><div className="container"><div className="error-state"><h3>{error}</h3><button className="btn btn-primary" style={{ marginTop: 18 }} onClick={load}>Try again</button></div></div></main>;
  return <main className="page"><div className="container"><div className="dashboard-header"><div><span className="eyebrow">Instructor studio</span><h1>Teach with clarity.</h1><p>Manage your courses, watch your reach, and keep improving the learning experience.</p></div><button className="btn btn-primary" onClick={() => navigate('/instructor/course/create')}><Plus size={17} /> Create course</button></div><div className="stats-grid"><div className="stat-card"><div className="stat-card-top"><span className="stat-label">Total courses</span><span className="stat-icon"><BookOpen size={17} /></span></div><div className="stat-value">{stats.total_courses || courses.length}</div></div><div className="stat-card"><div className="stat-card-top"><span className="stat-label">Total students</span><span className="stat-icon"><Users size={17} /></span></div><div className="stat-value">{stats.total_students || 0}</div></div><div className="stat-card"><div className="stat-card-top"><span className="stat-label">Average rating</span><span className="stat-icon"><Star size={17} /></span></div><div className="stat-value">{stats.average_rating || 0}</div></div><div className="stat-card"><div className="stat-card-top"><span className="stat-label">Revenue</span><span className="stat-icon"><DollarSign size={17} /></span></div><div className="stat-value">₹{stats.total_revenue || 0}</div></div></div><section className="panel"><div className="panel-head"><h2>Course performance</h2><BarChart3 size={19} color="var(--blue)" /></div>{courses.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Course</th><th>Level</th><th>Students</th><th>Rating</th><th>Actions</th></tr></thead><tbody>{courses.map((course) => <tr key={course.id}><td><strong>{course.title}</strong><div className="muted" style={{ marginTop: 4 }}>{course.domain}</div></td><td><span className="badge">{course.level}</span></td><td>{course.students || 0}</td><td>★ {course.rating || 0}</td><td><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}><Link className="btn btn-soft" to={`/instructor/course/edit/${course.id}`}>Edit</Link><Link className="btn btn-ghost" to={`/instructor/course/${course.id}/modules`}>Modules</Link><Link className="btn btn-ghost" to={`/instructor/course/${course.id}/lessons`}>Lessons</Link><Link className="btn btn-ghost" to={`/instructor/course/${course.id}/analytics`}>Analytics</Link><Link className="btn btn-ghost" to={`/instructor/course/${course.id}/students`}>Students</Link><button className="btn btn-danger" onClick={() => remove(course.id)}>Delete</button></div></td></tr>)}</tbody></table></div> : <div className="empty-state" style={{ border: 0, padding: '30px 0' }}><h3>Your teaching studio is ready</h3><p>Create your first course to start sharing what you know.</p><button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => navigate('/instructor/course/create')}><Plus size={15} /> Create course</button></div>}</section></div></main>;
};
export default InstructorDashboard;
