import { useState } from 'react';
import { ArrowLeft, Plus } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';

const InstructorCreateCourse = () => {
  const { user } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ title: '', description: '', domain: 'Programming', level: 'Beginner', price: 0, instructor: user?.name || '', course_url: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await api.post('/api/instructor/courses', { ...form, price: Number(form.price), course_url: form.course_url || null }); navigate('/instructor/dashboard'); } catch (requestError) { setError(requestError.response?.data?.detail || 'Could not create course'); } finally { setSaving(false); } };
  return <main className="page"><div className="container" style={{ maxWidth: 820 }}><Link to="/instructor/dashboard" className="nav-link" style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><ArrowLeft size={15} /> Back to dashboard</Link><div className="dashboard-header" style={{ marginTop: 22 }}><div><span className="eyebrow">Instructor studio</span><h1>Create a course</h1><p>Turn what you know into a clear, useful learning path.</p></div></div>{error && <div className="form-message" style={{ marginBottom: 18 }}>{error}</div>}<form className="panel" onSubmit={submit} style={{ display: 'grid', gap: 18 }}><div><label className="field-label" htmlFor="title">Course title</label><input className="input" id="title" name="title" value={form.title} onChange={update} placeholder="e.g. Python for practical data work" required /></div><div><label className="field-label" htmlFor="description">Description</label><textarea className="textarea" id="description" name="description" value={form.description} onChange={update} placeholder="What will learners be able to do after this course?" required /></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 14 }}><div><label className="field-label" htmlFor="domain">Topic</label><select className="select" id="domain" name="domain" value={form.domain} onChange={update}><option>Programming</option><option>Web Development</option><option>AI & ML</option><option>Data Science</option><option>Cybersecurity</option><option>Cloud Computing</option><option>DevOps</option><option>Mobile Development</option></select></div><div><label className="field-label" htmlFor="level">Level</label><select className="select" id="level" name="level" value={form.level} onChange={update}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 14 }}><div><label className="field-label" htmlFor="price">Price (₹)</label><input className="input" id="price" name="price" type="number" min="0" step=".01" value={form.price} onChange={update} /></div><div><label className="field-label" htmlFor="course_url">External course URL <span className="muted">(optional)</span></label><input className="input" id="course_url" name="course_url" type="url" value={form.course_url} onChange={update} placeholder="https://..." /></div></div><button className="btn btn-primary" type="submit" disabled={saving} style={{ justifySelf: 'start' }}><Plus size={16} /> {saving ? 'Creating...' : 'Create course'}</button></form></div></main>;
};
export default InstructorCreateCourse;
