import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, PlayCircle, Sparkles } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';

const LessonView = () => {
  const { courseId, lessonId } = useParams(); const { isAuthenticated } = useAuth(); const [course, setCourse] = useState(null); const [lesson, setLesson] = useState(null); const [lessons, setLessons] = useState([]); const [completed, setCompleted] = useState([]); const [enrolled, setEnrolled] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { const load = async () => { try { const courseResponse = await api.get(`/api/courses/${courseId}`); const all = (courseResponse.data.modules || []).flatMap((module) => (module.lessons || []).map((item) => ({ ...item, moduleTitle: module.title }))); setCourse(courseResponse.data); setLessons(all); setLesson(all.find((item) => item.id === Number(lessonId))); if (isAuthenticated) { const [enrollmentResponse, completionResponse] = await Promise.all([api.get('/api/enroll/'), api.get('/api/lesson-completions')]); const enrollmentData = enrollmentResponse.data?.data || enrollmentResponse.data || []; setEnrolled(enrollmentData.some((item) => item.course_id === Number(courseId))); setCompleted((completionResponse.data?.data || completionResponse.data || []).map((item) => item.lesson_id)); } } catch (requestError) { setError(requestError.response?.data?.detail || 'Could not load this lesson'); } finally { setLoading(false); } }; load(); }, [courseId, lessonId, isAuthenticated]);
  const markComplete = async () => { if (!enrolled || saving) return; setSaving(true); try { await api.post('/api/lesson-completions', { lesson_id: Number(lessonId), course_id: Number(courseId) }); setCompleted((current) => current.includes(Number(lessonId)) ? current : [...current, Number(lessonId)]); } catch (requestError) { setError(requestError.response?.data?.detail || 'Could not update progress'); } finally { setSaving(false); } };
  if (loading) return <main className="page"><div className="spinner" /></main>; if (!lesson || error) return <main className="page"><div className="container"><div className="error-state"><h3>{error || 'Lesson not found'}</h3><Link to={`/courses/${courseId}`} className="btn btn-primary" style={{ marginTop: 18 }}>Back to course</Link></div></div></main>;
  const index = lessons.findIndex((item) => item.id === Number(lessonId)); const next = lessons[index + 1]; const done = completed.includes(Number(lessonId));
  return <main className="page"><div className="container"><div className="lesson-layout"><aside className="lesson-sidebar"><p className="eyebrow">Course curriculum</p><h2>{course?.title}</h2><div>{lessons.map((item) => <Link className={`lesson-nav-link${item.id === Number(lessonId) ? ' current' : ''}`} key={item.id} to={`/course/${courseId}/lesson/${item.id}`}><span>{item.title}</span>{completed.includes(item.id) && <CheckCircle2 size={15} />}</Link>)}</div></aside><article className="lesson-content"><div className="muted" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '.82rem' }}><PlayCircle size={15} /> {lesson.moduleTitle}</div><h1>{lesson.title}</h1>{lesson.video_url && <div style={{ aspectRatio: '16 / 9', overflow: 'hidden', marginBottom: 22, background: '#eef2f9', borderRadius: 14 }}><iframe src={lesson.video_url.replace('watch?v=', 'embed/')} title={lesson.title} style={{ width: '100%', height: '100%', border: 0 }} allowFullScreen /></div>}{lesson.content ? <div className="lesson-text">{lesson.content}</div> : <div className="empty-state"><p>This lesson has no written content yet.</p></div>}<div className="lesson-actions"><Link to={`/courses/${courseId}`} className="btn btn-ghost"><ArrowLeft size={15} /> Course overview</Link><div style={{ display: 'flex', gap: 10 }}><button className={`btn ${done ? 'btn-soft' : 'btn-primary'}`} onClick={markComplete} disabled={done || !enrolled || saving}>{done ? <><CheckCircle2 size={15} /> Completed</> : saving ? 'Saving...' : 'Mark as complete'}</button>{next && <Link to={`/course/${courseId}/lesson/${next.id}`} className="btn btn-ghost">Next lesson <ArrowRight size={15} /></Link>}</div></div>{!enrolled && <p className="muted" style={{ marginTop: 18, fontSize: '.83rem' }}>Enroll in this course to track lesson completion. <Link to={`/courses/${courseId}`} style={{ color: 'var(--blue)', fontWeight: 700 }}>View course</Link></p>}<Link to="/ai" className="btn btn-soft" style={{ marginTop: 24 }}><Sparkles size={15} /> Ask AI about this lesson</Link></article></div></div></main>;
};
export default LessonView;
